/**
 * RemediationEngine — ⑤ 자가 치유의 오케스트레이터.
 *
 * 흐름: TriageVerdict(signal) → 범위 분류 → 초안 생성 → 회귀 증빙 → 게이트 → (자동 PR 가능 시) PR 생성.
 *
 * 강제되는 안전 불변:
 *  1) Remediation Lane 진입은 lane === "signal" 인 판정만 허용 (원칙 A: Retry/Quarantine은 진입 불가).
 *  2) scope === "none" 은 즉시 제외.
 *  3) 회귀 증빙이 passed가 아니면 PR 생성 금지 (gate가 차단).
 *  4) AI는 merge 권한 없음 — PR 생성까지만(PrPort에 merge 없음).
 */

import type { TriageVerdict, RemediationConfig } from "@qa/shared";
import { scopeFor } from "./scope.js";
import { gate } from "./gate.js";
import type {
  ProposalGenerator,
  FixVerifier,
  PrPort,
  ProposalRequest,
  RemediationProposal,
  ProposalStatus,
} from "./types.js";

export interface RemediationEngineDeps {
  readonly generator: ProposalGenerator;
  readonly verifier: FixVerifier;
  /** autoPr가 허용될 때만 호출. 없으면 PR 생성 단계 생략(needs_human_pr로 종료). */
  readonly prPort?: PrPort;
  /** caseId 조회: 서명 → 영향 케이스. */
  readonly caseIdsFor: (signature: string) => readonly string[];
  /** LLM 전송 전 PII/시크릿 마스킹 (R8). */
  readonly maskPII?: (text: string) => string;
}

export class RemediationEngine {
  constructor(private readonly deps: RemediationEngineDeps) {}

  /**
   * 단일 판정에 대해 수정 제안을 생성한다. Remediation 대상이 아니면 null.
   */
  async propose(
    verdict: TriageVerdict,
    config: RemediationConfig
  ): Promise<RemediationProposal | null> {
    // 안전 불변 1: signal 레인만 진입.
    if (verdict.lane !== "signal") return null;

    // 안전 불변 2: 코드로 못 고치는 분류는 제외.
    const scope = scopeFor(verdict.failureClass);
    if (scope === "none") return null;

    const mask = this.deps.maskPII ?? ((t) => t);
    const req: ProposalRequest = {
      signature: verdict.signature,
      failureClass: verdict.failureClass,
      scope,
      clusterMessage: mask(verdict.rationale),
      caseIds: this.deps.caseIdsFor(verdict.signature),
    };

    const draft = await this.deps.generator.generate(req);
    const proof = await this.deps.verifier.verify(draft, req);
    const gateResult = gate(scope, proof, config);

    let status: ProposalStatus;
    let prUrl: string | undefined;

    if (gateResult.blockedReasons.length > 0) {
      status = "blocked";
    } else if (gateResult.autoPrAllowed && this.deps.prPort) {
      // 안전 불변 4: PrPort.createPr만 호출 — merge는 존재하지 않음.
      const pr = await this.deps.prPort.createPr({
        title: `fix(${scope}): ${draft.summary}`.slice(0, 100),
        body: renderPrBody(req, draft, proof, gateResult),
        diff: draft.diff,
        scope,
      });
      prUrl = pr.url;
      status = "pr_opened";
    } else {
      // app_source이거나 자동 PR 비허용 → 사람이 PR/승인하도록 대기.
      status = "needs_human_pr";
    }

    return { signature: verdict.signature, scope, draft, regressionProof: proof, gate: gateResult, status, prUrl };
  }
}

/** PR 본문 — 검수에 필요한 근거·증빙·영향 범위·승인 요건을 모두 첨부한다. */
function renderPrBody(
  req: ProposalRequest,
  draft: { summary: string; rationale: string; affectedFiles: readonly string[]; source: string },
  proof: { status: string; evidence: string },
  gate: { requiredApprovals: number; codeownersRequired: boolean; scope: string }
): string {
  return [
    `## Automated remediation (${gate.scope})`,
    ``,
    `**Summary:** ${draft.summary}`,
    `**Rationale:** ${draft.rationale}`,
    `**Generated by:** ${draft.source} (no merge authority — human approval required)`,
    ``,
    `### Failure`,
    `- signature: \`${req.signature}\``,
    `- class: ${req.failureClass}`,
    `- affected cases: ${req.caseIds.length}`,
    ``,
    `### Regression proof`,
    `- status: **${proof.status}**`,
    `- ${proof.evidence}`,
    ``,
    `### Affected files`,
    ...draft.affectedFiles.map((f) => `- \`${f}\``),
    ``,
    `### Approval`,
    `- required approvals: ${gate.requiredApprovals}`,
    `- CODEOWNERS required: ${gate.codeownersRequired ? "yes" : "no"}`,
  ].join("\n");
}
